#!/bin/sh
#
# anerd: a Network Exchange Randomness Daemon client
#
#  Copyright (C) 2012-2013 Dustin Kirkland <dustin.kirkland@gmail.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, version 3 of the License.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

error() {
	echo "ERROR: $@" 1>&2
	exit 1
}

log() {
	printf "$(date '+%b %e %T') $(hostname) anerd[$$]: ${PROTO} $@\n" 1>&2
}

random_hash() {
	# Read and print random bytes
	head -c "${BYTES}" "${DEVICE}" | sha512sum | awk '{print $1}'
}

salt() {
	# Append timestamp-based salt to input
	cat
	local i=0
	while [ ${i} -lt ${BYTES} ] ; do
		n=$(date +%N | sed "s/^0\+//")
		printf "%x" ${n}
		i=$((i+1))
	done
}

salt_hash_and_write() {
	# Salt input, whiten with a hash, and write to device
	[ "${DEBUG}" = "1" ] && cat "${1}" 1>&2
	local bytes=$(wc -c "${1}" | awk '{print $1}')
	cat "${1}" "${1}.out" "${1}.err" | salt | sha512sum > "${DEVICE}"
	rm -f "${1}"
	log "client salted and hashed response from [${2}]"
}

udp_exchange() {
	local cmd=""
	case "${IPV6}" in
		true|TRUE|1)
			cmd="socat -v -t ${WAIT} UDP6-DATAGRAM:[${1}]:${2}"
		;;
		*)
			cmd="socat -v -t ${WAIT} - UDP-DATAGRAM:${1}:${2}"
		;;
	esac
	local f=$(mktemp -t "${PKG}.XXXXXXXXXXXX")
	log "client sent hashed entropy to [${1}:${2}]"
	(random_hash | $cmd >"${f}" 2>&1) || error "UDP network communication failed [$?]"
	salt_hash_and_write "${f}" ${1}:${2}
}

tcp_exchange() {
	local f1=$(mktemp -t "${PKG}.XXXXXXXXXXXX")
	local f2=$(mktemp -t "${PKG}.XXXXXXXXXXXX")
	printf "tag=" > "${f1}"
	cat "/var/lib/${PKG}/tag" >> "${f1}" || true
	# Create and enforce a challenge/response, to ensure personal communication
	local challenge=$(random_hash)
	local challenge_response=$(printf "${challenge}" | sha512sum | awk '{print $1}')
	printf "challenge=%s" "$challenge" > "${f2}"
	local cmd="curl ${CURL_OPTS} -o- -v --trace-time --connect-timeout 3 --max-time 3 --data @${f1} --data @${f2} ${1}"
	log "client sent hashed entropy to [${1}]"
	local f=$(mktemp -t "${PKG}.XXXXXXXXXXXX")
	($cmd >"${f}.out" 2>"${f}.err") || error "TCP network communication failed [$?]\n$(cat ${f})"
	[ "${challenge_response}" = $(head -n1 "${f}.out") ] || error "TCP server failed challenge/response [expected=${challenge_response}] != [got=$(head -n1 ${f}.out)]"
	log "client verified challenge/response with [${1}]"
	salt_hash_and_write "${f}" ${1}
}

broadcast() {
	local cmd="" dest=""
	case "${IPV6}" in
		true|TRUE|1)
			dest="ff02::1"
			cmd="socat -v -t ${WAIT} - UDP6-DATAGRAM:[${dest}]:${1}"
		;;
		*)
			dest="255.255.255.255"
			cmd="socat -v -t ${WAIT} - UDP-DATAGRAM:${dest}:${1},broadcast"
		;;
	esac
	log "client sent hashed entropy to [${dest}:${1}]"
	local f=$(mktemp -t "${PKG}.XXXXXXXXXXXX")
	(random_hash | $cmd >"${f}" 2>&1) || error "UDP network communication failed [$?]"
	salt_hash_and_write "${f}" ${dest}:${1}
}
# Source configuration
PKG="anerd"
[ -r "/etc/default/${PKG}-client" ] && . "/etc/default/${PKG}-client"
[ -r "${HOME}/.${PKG}rc" ] && . "${HOME}/.${PKG}rc"
while [ ! -z "$1" ]; do
	case "${1}" in
		-b|--broadcast)
			BROADCAST="1"
			shift
		;;
		-c|--curl-opts)
			CURL_OPTS="$2"
			shift 2
		;;
		-d|--device)
			DEVICE="$2"
			shift 2
		;;
		--debug)
			DEBUG="1"
			shift
		;;
		--insecure)
			CURL_OPTS="${CURL_OPTS} --insecure"
			shift
		;;
		-s|--server)
			POOL="${POOL} $2"
			shift 2
		;;
		-t|--tcp)
			PROTO="tcp"
			shift
		;;
		-u|--udp)
			PROTO="udp"
			shift
		;;
		-w|--wget-opts)
			WGET_OPTS="$2"
			shift 2
		;;
		*)
			error "Unknown options [$1]"
		;;
	esac
done
[ -n "${DEVICE}" ] || DEVICE="/dev/urandom"
[ -n "${IPV6}" ] || IPV6=false
[ -n "${BYTES}" ] || BYTES=64
[ -n "${WAIT}" ] || WAIT="0.1"
[ -n "${PROTO}" ] || PROTO="tcp"
if [ "${PROTO}" = "udp" ]; then
	if [ -z "${POOL}" ]; then
		POOL="${POOL_UDP}"
		if [ -z "${POOL}" ]; then
			error "No servers configured in pool"
		fi
	fi
	command -v socat || error "You will need to install the suggested 'socat' package to use the udp client"
	# Loop over servers configured in the pool
	for i in ${POOL}; do
		# Get the hostname/ip
		h=${i%%:*}
		# Get the port, or set to default
		p=${i##*:}
		[ "${h}" = "${p}" ] && p="26373"
		[ -n "${h}" ] || continue
		udp_exchange "${h}" "${p}"
	done
	if [ "${BROADCAST}" = "1" ]; then
		# Now broadcast to the local network
		broadcast 26373 || true
	fi
elif [ "${PROTO}" = "tcp" ]; then
	if [ -z "${POOL}" ]; then
		POOL="${POOL_TCP}"
		if [ -z "${POOL}" ]; then
			error "No servers configured in pool"
		fi
	fi
	command -v curl || error "You will need to install the 'curl' package to use the udp client"
	# Default is TCP
	for i in ${POOL}; do
		tcp_exchange "${i}"
	done
else
	error "Invalid protocol"
fi
