.TH anerd 1 "28 November 2012" anerd "anerd server"
.SH NAME
\fBanerd\fP \- asynchronous network exchanged randomness daemon server

.SH SYNOPSIS
\fBanerd\fP [-6] [-d \fIdevice\fR] [-s \fIsize\fR] [-p \fIport\fR]

.SH DESCRIPTION
\fBanerd\fP is the asynchronous network exchanged randomness daemon server.  This daemon will gather and respond to network requests for entropy on UDP port 26373.

The server will run as a daemon and listen on UDP port 26373. Whenever it receives data, it hashes the data and salts it with the sum of all of the time-stamps from data being received since the server started, before writing the data to /dev/urandom, or whatever device is set with the command line parameters. It then responds to the sender with random bytes for the sender to write to /dev/urandom. This can be used to exchange entropy between machines making it possible for virtual machines to receive entropy from machines capable of generating it.

.SH OPTIONS
.TP
.B \-6
enables ipv6 support
.TP
.B \-d \fIdevice\fR
sets randomness device to read from and write to
.TP
.B \-s \fIsize\fR
sets data size in bytes
.TP
.B \-p \fIport\fR
sets port

.SH SEE ALSO
\fBanerd\-client(1)\fP

.SH AUTHOR
This utility was written by Dustin Kirkland <dustin.kirkland@gmail.com>. This man page was written by Wesley Wiedenmeier <magicalchicken@mail.magicalchicken.dnsdynamic.net>.
