.TH anerd-server-tcp 1 "07 February 2013" anerd "anerd server"
.SH NAME
\fBanerd-server-tcp\fP \- a network exchanged randomness daemon web server

.SH SYNOPSIS
\fBanerd-server-tcp\fP [PORT]

.SH DESCRIPTION
\fBanerd-server-tcp\fP is a web version of a network exchanged randomness daemon server.

This daemon will gather and respond to network requests for entropy on a specified TCP port.

If the port is 443, it will serve HTTPS requests, using the key at \fI/etc/anerd-server/key.pem\fP and the cert at \fI/etc/anerd-server/cert.pem\fP.  Otherwise, it will server HTTP requests.

.SH SEE ALSO
\fBanerd\fP(1), \fBanerd\-client\fP(1)

.SH AUTHOR
This utility and manpage was written by Dustin Kirkland <dustin.kirkland@gmail.com>.
