.TH pollinate 1 "28 November 2012" pollinate "pollinate"
.SH NAME
pollinate \- an Entropy-as-a-Service client

.SH SYNOPSIS
\fBpollinate\fP [-c|--curl-opts CURL_OPTS] [-d|--device DEVICE] [-i|--insecure] [-n|--no-challenge] [-r|--reseed] [-s|--server SERVER1 [-s|--server SERVER2] ...]

.SH DESCRIPTION
\fBpollinate\fP is an entropy as a service client.  It will fetch a random seed from one or more remote servers, and feed those into a (pseudo) random number generator.  This is often useful in cloud and virtual machine environments with limited sources of entropy.

.SH OPTIONS
.TP
\fB-b|--binary\fP
rather than producing hex text sha512sum(1) output, convert each two hex digits into a byte of binary data
.TP
\fB-c|--curl-opts\fP CURL_OPTS
options to pass through to \fBcurl\fP(1)
.TP
\fB-d|--device\fP DEVICE
device to seed (default is \fI/dev/urandom\fP); note, you can use - to print to stdout
.TP
\fB-n|--no-challenge\fP
disable the challenge/response portion of the protocol; this enables a compatibility mode to speak to any entropy server, like random.org or news.google.com
.TP
\fB-i|--insecure\fP
ignore SSL/TLS certificate errors (use of this option is highly discouraged)
.TP
\fB-p|--pool\fP SERVER
remote \fBpollen\fP(8) server pool to interact with; this option can be specified multiple times to interact with multiple servers in a pool
.TP
\fB-r|--reseed\fP
by default, \fBpollinate\fP technically only needs to run successfully once ever; this option should be used if someone wants run more than once, and re-seed the PRNG
.TP
\fB-s|--server\fP SERVER
remote \fBpollen\fP(8) server to interact with; if this option is used, the pool is ignored, and only a single server is used
.TP
\fB--strict\fP
handle network errors strictly and exit non-zero for any network error encountered, otherwise default is to warn
.TP
\fB-t|--testing\fP
test communications with the \fBpollen\fP(8) server; note that this will NOT actually seed your PRNG, but only verify that the local client can communicate with the remote servers; note that this option forces DEVICE to stdout
.TP
\fB-q|--quiet\fP
silence any log messages
.TP
\fB-w|--wait\fP WAIT
time in seconds you're willing to wait for a response from the server

.SH SEE ALSO
\fBpollen\fP(8)

.SH AUTHOR
This manpage and the utility were written by Dustin Kirkland <kirkland@ubuntu.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL, or on the web at \fIhttp://www.gnu.org/licenses/gpl.txt\fP.
