#!/bin/sh
#
# pollinate: an Entropy-as-a-Service client
#
#  Copyright (C) 2012-2013 Dustin Kirkland <dustin.kirkland@gmail.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, version 3 of the License.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

PKG="pollinate"
TMPDIR=$(mktemp -d -t "${PKG}.XXXXXXXXXXXX")
trap "rm -rf ${TMPDIR} 2>/dev/null || true" EXIT HUP INT QUIT TERM

error() {
	echo "ERROR: $@" 1>&2
	exit 1
}

log() {
	[ "${QUIET}" = "1" ] || printf "$(date '+%b %e %T') $(hostname) ${PKG}[$$]: $@\n" 1>&2
}

random_hash() {
	# Read and print urandom bytes
	head -c "${BYTES}" /dev/urandom | sha512sum | awk '{print $1}'
}

salt() {
	# Append timestamp-based salt to input
	cat
	local i=0
	while [ ${i} -lt ${BYTES} ] ; do
		n=$(date +%N | sed "s/^0\+//")
		printf "%x" ${n}
		i=$((i+1))
	done
}

salt_hash_and_write() {
	# Salt input, whiten with a hash, and write to device
	if [ "${DEVICE}" = "-" ]; then
		cat "${TMPDIR}/out" "${TMPDIR}/err" | salt | sha512sum | awk '{print $1}'
	else
		cat "${TMPDIR}/out" "${TMPDIR}/err" | salt | sha512sum | awk '{print $1}' > "${DEVICE}"
	fi
	log "client salted and hashed response from [${1}]"
}

exchange() {
	local server="${1}"
	local f1="${TMPDIR}/tag"
	local f2="${TMPDIR}/challenge"
	case "${server}" in
		"http://"*)
			error "Pollen server only responds on https"
		;;
		"https://"*)
			# looks good
			true
		;;
		*)
			# prepend https
			server="https://${server}"
		;;
	esac
	printf "tag=" > "${f1}"
	cat "/var/lib/${PKG}/tag" 2>/dev/null >> "${f1}" || true
	# Create and enforce a challenge/response, to ensure personal communication
	local challenge=$(random_hash)
	local challenge_response=$(printf "${challenge}" | sha512sum | awk '{print $1}')
	printf "challenge=%s" "$challenge" > "${f2}"
	local cmd="curl ${CURL_OPTS} -o- -v --trace-time --connect-timeout ${WAIT} --max-time ${WAIT} --data @${f1} --data @${f2} ${server}"
	log "client sent challenge to [${1}]"
	local out="${TMPDIR}/out"
	local err="${TMPDIR}/err"
	($cmd >"${out}" 2>"${err}") || error "Network communication failed [$?]\n$(cat ${out} ${err})"
	[ "${challenge_response}" = $(head -n1 "${out}") ] || error "Server failed challenge/response [expected=${challenge_response}] != [got=$(head -n1 ${out})]"
	log "client verified challenge/response with [${server}]"
	salt_hash_and_write "${server}"
}

# Source configuration
[ -r "/etc/default/pollinate" ] && . "/etc/default/pollinate"
[ -r "${HOME}/.${PKG}rc" ] && . "${HOME}/.${PKG}rc"
while [ ! -z "$1" ]; do
	case "${1}" in
		-c|--curl-opts)
			CURL_OPTS="$2"
			shift 2
		;;
		-d|--device)
			DEVICE="$2"
			shift 2
		;;
		-i|--insecure)
			CURL_OPTS="${CURL_OPTS} --insecure"
			shift
		;;
		-s|--server)
			POOL="${POOL} $2"
			shift 2
		;;
		-q|--quiet)
			QUIET=1
			shift
		;;
		-w|--wait)
			WAIT="$2"
			shift 2
		;;
		*)
			error "Unknown options [$1]"
		;;
	esac
done
[ -n "${DEVICE}" ] || DEVICE="/dev/urandom"
[ -n "${IPV6}" ] || IPV6=false
[ -n "${BYTES}" ] || BYTES=64
[ -n "${WAIT}" ] || WAIT="3"
if [ -z "${POOL}" ]; then
	error "No servers configured in pool"
fi
for i in ${POOL}; do
	exchange "${i}"
done
