.TH pollinate 1 "28 November 2012" pollinate "pollinate"
.SH NAME
pollinate \- an Entropy-as-a-Service client

.SH SYNOPSIS
\fBpollinate\fP [-c|--curl-opts CURL_OPTS] [-d|--device DEVICE] [-i|--insecure] [-s|--server SERVER]

.SH DESCRIPTION
\fBpollinate\fP is an entropy as a service client.  It will fetch a random seed from one or more remote servers, and feed those into a (pseudo) random number generator.  This is often useful in cloud and virtual machine environments with limited sources of entropy.

.SH OPTIONS
.TP
\fB-c|--curl-opts\fP CURL_OPTS
options to pass through to \fBcurl\fP(1)
.TP
\fB-d|--device\fP DEVICE
device to seed (default is \fI/dev/urandom\fP); note, you can use - to print to stdout
.TP
\fB-i|--insecure\fP
ignore SSL/TLS certificate errors (use of this option is highly discouraged)
.TP
\fB-s|--server\fP SERVER
remote \fBpollen\fP(8) server to interact with
.TP
\fB-q|--quiet\fP
silence any log messages
.TP
\fB-w|--wait\fP WAIT
time in seconds you're willing to wait for a response from the server

.SH SEE ALSO
\fBpollen\fP(8)

.SH AUTHOR
This manpage and the utility were written by Dustin Kirkland <kirkland@ubuntu.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL, or on the web at \fIhttp://www.gnu.org/licenses/gpl.txt\fP.
