.TH pollen 1 "07 February 2013" pollen "pollen server"
.SH NAME
\fBpollen\fP \- Entropy-as-a-Service web server

.SH SYNOPSIS
\fBpollen\fP [PORT]

.SH DESCRIPTION
\fBpollen\fP is a web version of a network exchanged randomness daemon server.

This daemon will gather and respond to network requests for entropy on a specified port.

All requests are serviced over HTTPS, using the key at \fI/etc/pollen/key.pem\fP and the cert at \fI/etc/pollen/cert.pem\fP.

.SH SEE ALSO
\fBpollen\fP(1), \fBpollinate\fP(1)

.SH AUTHOR
This manpage and the utility were written by Dustin Kirkland <kirkland@ubuntu.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL, or on the web at \fIhttp://www.gnu.org/licenses/gpl.txt\fP.
