.TH pollen 1 "07 February 2013" pollen "pollen server"
.SH NAME
\fBpollen\fP \- an Entropy-as-a-Service web server

.SH SYNOPSIS
\fBpollen\fP HTTP_PORT HTTPS_PORT DEVICE

.SH OPTIONS

\fBHTTP_PORT\fP - the http port on which to listen and serve clear text responses; use 0 to disable; default is 80

\fBHTTPS_PORT\fP - the https port on which to listen and serve encrypted, TLS responses; use 0 to disable; default is 443

\fBDEVICE\FP - the device to use for reading and writing random data; default is \fI/dev/urandom\fP

\fBNOTE: All of these must be specified!!!\fP

.SH DESCRIPTION
\fBpollen\fP is an Entropy-as-a-Service web server, providing random seeds over a TLS encrypted connection.

All requests are serviced over HTTPS, using the key at \fI/etc/pollen/key.pem\fP and the cert at \fI/etc/pollen/cert.pem\fP.

Some configuration options are available to the system administrator in \fI/etc/default/pollen\fP.

.SH SEE ALSO
\fBpollen\fP(1), \fBpollinate\fP(1)

.SH AUTHOR
This manpage and the utility were written by Dustin Kirkland <kirkland@ubuntu.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL, or on the web at \fIhttp://www.gnu.org/licenses/gpl.txt\fP.
