#!/bin/sh
#
# anerd: Seed RNG at boot with aNerd data
#
#  Copyright (C) 2012-2013 Dustin Kirkland <dustin.kirkland@gmail.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, version 3 of the License.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

case "$1" in
	# no pre-reqs
	prereqs) echo ""; exit 0;;
esac

. /scripts/functions
configure_networking

# Retrieve entropy from network source
export PATH="$PATH:/bin"
ANERD_URLS="$(cat /etc/anerd_server)"
if [ -n "$ANERD_URLS" ]; then
	curl -4 --connect-timeout 1 --max-time 1 --trace /dev/urandom --trace-time --output /dev/urandom --url $ANERD_URLS >/dev/urandom 2>/dev/.initramfs/anerd
fi
