#!/bin/sh -e

PKG="pollen"
DIR="/etc/$PKG"
mkdir -p -m 700 "$DIR"
PUB_CERT="$DIR/cert.pem"
PK="$DIR/key.pem"
CA="$DIR/ca.pem"

if [ ! -r "$PUB_CERT" ] || [ ! -r "$PK" ]; then
	install -m 600 /dev/null "$PUB_CERT"
	install -m 600 /dev/null "$PK"
	# Auto generate self signed certs if we don't have one already in place
	openssl req -new -newkey rsa:4096 -nodes -x509 -out "$PUB_CERT" -keyout "$PK" -days 3650 -subj "/C=XX/ST=XX/L=XXXX/CN=XXXXXXXX/emailAddress=noone@example.com"
fi

#DEBHELPER#
